#!/usr/bin/env python
# license removed for brevity
import rospy
from std_msgs.msg import Float64
import math

joint_controller = rospy.Publisher('/cart_robot/joint1_position_controller/command', Float64, queue_size=10)
add_shake = rospy.get_param("add_shake/add_shake")

if add_shake:
    max_angle = 5.0
else:
    max_angle = 0.0

def talker():
    global max_angle
    shake_time = 3.0
    # max_angle = 5.0
    rospy.init_node('talker', anonymous=True)
    rate = rospy.Rate(60) # 60hz
    init_time = rospy.get_time()
    rospy.loginfo("init")
    while not rospy.is_shutdown():
        time = rospy.get_time() - init_time
        deg = math.pi / 180.0 * max_angle * math.sin(2*math.pi*time/shake_time)
        joint_controller.publish(deg)
        rate.sleep()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
